[[redirects]]
  from = "/pokemessages"
  to = "/HTML/page1.html"
  status = 200

[[redirects]]
  from = "/pokememories"
  to = "/HTML/page2.html"
  status = 200

[[redirects]]
  from = "/pokemusic"
  to = "/HTML/page3.html"
  status = 200

[[redirects]]
  from = "/*/*"
  to = "/"
  status = 200

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
